# Site
repository: andersgb/andersgb.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anders Granskogen Bjørnstad
title: Software and tech things
email: "@".join(["andersgb", "gmail.com"])
website: andersgb.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: granskog1
github_username:  andersgb
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: granskog1
linkedin_username: andersgb
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Anders Granskogen Bjørnstad and I like building things with software. I have an MSc in Applied Physics and my early career started with developing numerical simulation software. Working with computational fluid- and thermo-dynamics I kinda stumbled into high performance computing, mathematical modeling and numerical optimization (gradient descent!). This transitioned into software engineering more broadly and, importantly, data science and machine learning. I am currently working in Axbit, a software consultancy company, where I've had many different roles (including ~1 year as CEO). What I enjoy most at Axbit is solving (and shipping solutions to!) hard problems for our customers. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        # link_text: Project Website
        quote: >
          An unfinished CV page means the person has more important things to get done
        description: | # this will include new lines to allow paragraphs
          :)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Moved to Molde (Norway) in 2017 which turned out to be the best life hack ever. I love rock climbing. See my tick list on [8a.nu](https://www.8a.nu/user/anders-granskogen-bjornstad/sportclimbing). 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
