# Site
repository: andersgb/andersgb.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anders Granskogen Bjørnstad
title: Software and tech things
email: |
    "@".join(["andersgb", "gmail.com"])
website: andersgb.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: granskog1
github_username:  andersgb
instagram_username: granskog1
linkedin_username: andersgb

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Anders Granskogen Bjørnstad and I like building things with software. I have an MSc in Applied Physics and my early career started with developing numerical simulation software. Working with computational fluid- and thermo-dynamics I kinda stumbled into high performance computing, mathematical modeling and numerical optimization. I worked with linear algebra packages and implemented various optimization methods, including gradient descent. Later, this transitioned into software engineering more broadly and, importantly, data science and machine learning. I also realized that I like contributing to startups and creating new things, because that's where everything is about building and succeeding and just doing what's necessary, less about all the other work fuss. I am currently working in Axbit, a software consultancy company, where I've had several different roles (including ~1 year as CEO). What I enjoy most at Axbit is solving (and shipping solutions to!) hard problems for our customers. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        # link_text: Project Website
        quote: >
          An unfinished CV page means the person has more important things to get done
        description: | # this will include new lines to allow paragraphs
          :)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Moved to Molde (Norway) in 2017 which turned out to be the best life hack ever. I love rock climbing. See my tick list on [8a.nu](https://www.8a.nu/user/anders-granskogen-bjornstad/sportclimbing). 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
